name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npm run build:ts
      - run: npm run lint:ci

      - name: Restore emscripten build cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            .emscripten_cache
          key: 1-emscripten-${{ hashFiles('build.sh') }}
          restore-keys: |
            1-emscripten-

      - run: npm run build:wasm

      # Catch Node import failures that don't reproduce in Jest <https://github.com/foxglove/wasm-bz2/issues/4>
      - run: node -e 'require("./dist/index.js").default.init()'

      - run: npm run test

      - name: Publish to NPM
        if: ${{ startsWith(github.ref, 'refs/tags/v') && matrix.node-version == '16.x' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
